name: Terraform Provisioning

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Provision Infraestrutura na AWS
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} #chave e secret da AWS (não cadastrados)
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} #chave e secret da AWS (não cadastrados)
      AWS_DEFAULT_REGION: us-east-1 # ajuste para sua região

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Inicializar Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Validar configuração
        run: terraform validate
        working-directory: ./terraform

      - name: Planejar infraestrutura
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      - name: Aplicar infraestrutura
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform